server:
  port: 9099

## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.5.39:3306/intelligent_res?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root1
    password: wk3mFzikZiznbwCE

  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    request-context-attribute: req
    config: setTimeFormat("HH:mm:ss")
  ## 启用热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis-plus:
  mapper-locations: classpath*:/mappers/*/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: is_valid # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值
